#!/usr/bin/env Rscript

#' check if R_LIBS_USER writable
#' @param path directory path
check.writable <- function(path) {
  # check if writable
  tryCatch(dir.create(paste0(path,"/ledger-plots.dummy")),
           warning = function(w) {return(FALSE)},
           finally = {unlink(paste0(path,"/ledger-plots.dummy"),
                             recursive = TRUE)})
}

#' Install missing packages for this script
install.missing.packages <- function() {

  # check that R_LIBS_USER directory is writable
  if (!check.writable(Sys.getenv("R_LIBS_USER"))) {
    stop(paste("Directory",Sys.getenv("R_LIBS_USER"),
               "is not writable (configure Renviron (/etc/Renviron))."))
  }

  # argument parsing
  if (!require("optparse")) install.packages("optparse")


  # devtools for installing ledgerplots package
  if (!require("devtools")) install.packages("devtools")

  # install ledger-plots
  require("devtools")
  install_github("esovetkin/ledger-plots/ledgerplots")
}

# to install missing dependencies
if (any(c("--install-dependencies","-u") %in% commandArgs(trailingOnly = TRUE))) {
  install.missing.packages()
}

# parse arguments
if (!require("optparse", quietly = TRUE)) {
  stop("optparse R-package is missing! Use -u,--install-dependencies")
}
require("optparse", quietly = TRUE)

# available options
option_list <- list(
  make_option(c("-o","--output"), type="character", default="ledger.pdf",
              help = "output pdf file name", metavar="character"),
  make_option(c("-q","--queries"), type="character", default=NULL,
              help =
                "multiple queries separated by ';;' for transactions to plot",
              metavar="character"),
  make_option(c("-f","--functions"), type="character",
              default="cumsum",
              help = paste0("functions separated by ';;'  applied to transactions vector. ",
                            "Can be any R-function. Useful examples: cumsum, monthly."),
              metavar="character"),
  make_option(c("--order-function"), type="character",
              default="function(x) sum(abs(x))",
              help = "function that specifies how to order the plots",
              metavar="character"),
  make_option(c("-l","--ledger-options"), type="character", default=NULL,
              help = "string with options given to ledger",
              metavar="character"),
  make_option(c("--ledger-bin-path"), type="character", default=NULL,
              help = "path to the ledger executable",
              metavar="character"),
  make_option(c("-u","--install-dependencies"), action = "store_true", default = FALSE,
              help = "install missing dependencies. It also updates ledgerplots package")
)

opt_parser <- OptionParser(option_list = option_list,
                           prog = "ledger-plots",
                           description =
                             paste0("Using ledger get and plot transactions to a pdf file. ",
                                    "You may specify the query in -q options. The program plots ",
                                    "the daily value of the function evaluated on the transactions. ",
                                    "The function can be specified in -f option.\n\n",
                                    "Multiple plots are ordered with respect to the depth of the ",
                                    "account names (e.g. Assets:Cash has depth 2) and function ",
                                    "evaluated on transactions vector (--order-function argument).\n\n",
                                    "Extra option to be passed to ledger may be specified using the ",
                                    "--ledger-options argument.\n\n",
                                    "In case your ledger executable file is located in a non-$PATH directory ",
                                    "then you can specify the correct path with --ledger-bin-path argument.\n\n",
                                    "You can install missing R-package dependencies using the ",
                                    "--install-dependencies argument. This also updates the ",
                                    "ledgerplots R-package."),
                           epilogue =
                             paste0("Examples:\n\n",
                                    "Install dependencies and update ledgerplots R-package:\n",
                                    "ledger-plots -u\n\n",
                                    "Generate plot for assets:\n",
                                    "ledger-plots -q \"^assets: -X EUR\" -f \"cumsum\"\n\n"))
opt <- parse_args(opt_parser)

# in case there are some queries, plot them
if (! is.null(opt$queries)) {

  if (!require("ledgerplots", quietly = TRUE)) {
    stop("ledgerplots R-package is missing! Use -u,--install-dependencies")
  }
  require("ledgerplots", quietly = TRUE)

  # split on queries and functions
  q <- unlist(strsplit(opt$queries,split=";;"))
  f <- unlist(strsplit(opt$functions,split=";;"))

  # make functions the same length
  if (length(f) < length(q)) {
    f <- f[(1:length(q) - 1) %% length(f) + 1]
  }

  # create a pdf device
  pdf(opt$output, width = 13, height = 7, onefile = TRUE)

  # graphical parameters (4 plots per page, see more ?par)
  par(mex=1.2,mar=c(6,4,1,1), mfcol=c(2,2))

  # make plot for each query
  for (i in 1:length(q)) {
    query.plot(q[i],
               order.function = function(x)
                 do.call(eval(parse(text=opt$"order-function")),args=list(x)),
               ledger.options = opt$"ledger-options",
               ledger.path = opt$"ledger-bin-path",
               FUN=function(x)
                 do.call(eval(parse(text=f[i])),args=list(x))
               )
  }

  # close pdf device
  dev.off()
}
